<?php

use Illuminate\Database\Seeder;

class DistrosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$distros = array(
			array(
				"type" => "ftp",
				"host" => "distro.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro1.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro1.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro1.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro2.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro2.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro2.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro3.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro3.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro3.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro4.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro4.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro4.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro5.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro5.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro5.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro6.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro6.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro6.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro7.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro7.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro7.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro8.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro8.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro8.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro9.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro9.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro9.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro10.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro10.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro10.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro11.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro11.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro11.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro12.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro12.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro12.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro13.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro13.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro13.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro14.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro14.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro14.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro15.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro15.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro15.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro16.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro16.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro16.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro17.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro17.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro17.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro18.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro18.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro18.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro19.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro19.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro19.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro20.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro20.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro20.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro21.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro21.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro21.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro22.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro22.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro22.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro23.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro23.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro23.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro24.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro24.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro24.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro25.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro25.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro25.txt",
			),
			array(
				"type" => "ftp",
				"host" => "distro26.lastverteiler.net",
				"port" => 21,
				"username" => "EdytaKrysciak949",
				"password" => "0ddb2419a4ec",
				"index_url" => "https://distro.lastverteiler.net/distro26.indexLONG.txt",
				"listing_url" => "http://s01.hq-mirror.de/distro/ListingDistro26.txt",
			),
		);
		
		foreach($distros as $distro) {
			$data = array_merge($distro, [
				'created_at' => DB::raw('NOW()'),
				'updated_at' => DB::raw('NOW()'),
			]);
	        DB::table('distros')->insert($data);
		}

    }
}
