<?php

use Illuminate\Database\Seeder;

class StationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$stations = array(
			array(
				"tvprogram_name" => "2plus2",
				"otrkeyfile_name" => "2plus2",
				"language" => "Ukrainisch",
				"language_short" => "uk",
			),
			array(
				"tvprogram_name" => "3PLUS",
				"otrkeyfile_name" => "3plus",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "3sat",
				"otrkeyfile_name" => "3sat",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "4PLUS",
				"otrkeyfile_name" => "4plus",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ANIXE",
				"otrkeyfile_name" => "anixe",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ANTENA3",
				"otrkeyfile_name" => "antena3",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "ARD",
				"otrkeyfile_name" => "ard",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ARD EINSFESTIVAL",
				"otrkeyfile_name" => "ardeinsfestival",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ARD EINSPLUS",
				"otrkeyfile_name" => "ardeinsplus",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ARTE",
				"otrkeyfile_name" => "arte",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ARTEFR",
				"otrkeyfile_name" => "artefr",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "ASTROTV",
				"otrkeyfile_name" => "astrotv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ATV",
				"otrkeyfile_name" => "atv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "BAY3",
				"otrkeyfile_name" => "bay3",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "BBC WORLD",
				"otrkeyfile_name" => "bbcworld",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "BIBELTV",
				"otrkeyfile_name" => "bibeltv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "BLOOMBERG",
				"otrkeyfile_name" => "bloomberg",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "BR ALPHA",
				"otrkeyfile_name" => "bralpha",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "CNBC",
				"otrkeyfile_name" => "cnbc",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "CNN",
				"otrkeyfile_name" => "cnn",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "CUATRO",
				"otrkeyfile_name" => "cuatro",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "DAF",
				"otrkeyfile_name" => "daf",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "DELUXEMUSIC",
				"otrkeyfile_name" => "deluxemusic",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "DISNEY",
				"otrkeyfile_name" => "disney",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "DMAX",
				"otrkeyfile_name" => "dmax",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "DMF",
				"otrkeyfile_name" => "dmf",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ERF",
				"otrkeyfile_name" => "erf",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "EURONEWS",
				"otrkeyfile_name" => "euronews",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "EUROSPORT",
				"otrkeyfile_name" => "eurosport",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "FDFTELECINCO",
				"otrkeyfile_name" => "fdftelecinco",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "FRANCE2",
				"otrkeyfile_name" => "france2",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "FRANCE3",
				"otrkeyfile_name" => "france3",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "FRANCE4",
				"otrkeyfile_name" => "france4",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "FRANCE5",
				"otrkeyfile_name" => "france5",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "FRANKENTV",
				"otrkeyfile_name" => "frankentv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "GOTV",
				"otrkeyfile_name" => "gotv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "HR3",
				"otrkeyfile_name" => "hr3",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ITALIA1",
				"otrkeyfile_name" => "italia1",
				"language" => "Italienisch",
				"language_short" => "it",
			),
			array(
				"tvprogram_name" => "JOIZ",
				"otrkeyfile_name" => "joiz",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "KABEL 1",
				"otrkeyfile_name" => "kabel1",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "KIKA",
				"otrkeyfile_name" => "kika",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "KTV",
				"otrkeyfile_name" => "ktv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "LA1",
				"otrkeyfile_name" => "la1",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "LA2",
				"otrkeyfile_name" => "la2",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "LASEXTA",
				"otrkeyfile_name" => "lasexta",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "M6",
				"otrkeyfile_name" => "m6",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "MDR",
				"otrkeyfile_name" => "mdr",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "MUENCHENTV",
				"otrkeyfile_name" => "muenchentv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "N24",
				"otrkeyfile_name" => "n24",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "NDR",
				"otrkeyfile_name" => "ndr",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "NEOX",
				"otrkeyfile_name" => "neox",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "NICK",
				"otrkeyfile_name" => "nickelodeon",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "NICKELODEON",
				"otrkeyfile_name" => "nickelodeon",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "NOVA",
				"otrkeyfile_name" => "nova",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "NTV",
				"otrkeyfile_name" => "ntv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ORF1",
				"otrkeyfile_name" => "orf1",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ORF2",
				"otrkeyfile_name" => "orf2",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ORF3",
				"otrkeyfile_name" => "orf3",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "PERWY",
				"otrkeyfile_name" => "perwy",
				"language" => "Russisch",
				"language_short" => "ru",
			),
			array(
				"tvprogram_name" => "PHOENIX",
				"otrkeyfile_name" => "phoenix",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "PRO7",
				"otrkeyfile_name" => "pro7",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "PRO7MAXX",
				"otrkeyfile_name" => "pro7maxx",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "QLAR",
				"otrkeyfile_name" => "qlar",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "RAI1",
				"otrkeyfile_name" => "rai1",
				"language" => "Italienisch",
				"language_short" => "it",
			),
			array(
				"tvprogram_name" => "RAI2",
				"otrkeyfile_name" => "rai2",
				"language" => "Italienisch",
				"language_short" => "it",
			),
			array(
				"tvprogram_name" => "RAI3",
				"otrkeyfile_name" => "rai3",
				"language" => "Italienisch",
				"language_short" => "it",
			),
			array(
				"tvprogram_name" => "RBB",
				"otrkeyfile_name" => "rbb",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "RIC",
				"otrkeyfile_name" => "ric",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "RNF",
				"otrkeyfile_name" => "rnf",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "RTL",
				"otrkeyfile_name" => "rtl",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "RTL2",
				"otrkeyfile_name" => "rtl2",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "RTLNITRO",
				"otrkeyfile_name" => "rtlnitro",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "RTRPLANETA",
				"otrkeyfile_name" => "rtrplaneta",
				"language" => "Russisch",
				"language_short" => "ru",
			),
			array(
				"tvprogram_name" => "SAT1",
				"otrkeyfile_name" => "sat1",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SAT1CH",
				"otrkeyfile_name" => "sat1ch",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SAT1GOLD",
				"otrkeyfile_name" => "sat1gold",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SF1",
				"otrkeyfile_name" => "sf1",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SF2",
				"otrkeyfile_name" => "sf2",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SFINFO",
				"otrkeyfile_name" => "sfinfo",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SIXX",
				"otrkeyfile_name" => "sixx",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SPORT1",
				"otrkeyfile_name" => "sport1",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SRTL",
				"otrkeyfile_name" => "srtl",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "STV",
				"otrkeyfile_name" => "stv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SW3",
				"otrkeyfile_name" => "sw3",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "TAGESSCHAU24",
				"otrkeyfile_name" => "tagesschau24",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "TELE5",
				"otrkeyfile_name" => "tele5",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "TELECINCO",
				"otrkeyfile_name" => "telecinco",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "TF1",
				"otrkeyfile_name" => "tf1",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "TLC",
				"otrkeyfile_name" => "tlc",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "TRT",
				"otrkeyfile_name" => "trt",
				"language" => "Türkisch",
				"language_short" => "tr",
			),
			array(
				"tvprogram_name" => "TV5",
				"otrkeyfile_name" => "tv5",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "TVPHISTORIA",
				"otrkeyfile_name" => "tvphistoria",
				"language" => "Polnisch",
				"language_short" => "pl",
			),
			array(
				"tvprogram_name" => "TVPINFO",
				"otrkeyfile_name" => "tvpinfo",
				"language" => "Polnisch",
				"language_short" => "pl",
			),
			array(
				"tvprogram_name" => "TVPKULTURA",
				"otrkeyfile_name" => "tvpkultura",
				"language" => "Polnisch",
				"language_short" => "pl",
			),
			array(
				"tvprogram_name" => "TVPOLONIA",
				"otrkeyfile_name" => "tvpolonia",
				"language" => "Polnisch",
				"language_short" => "pl",
			),
			array(
				"tvprogram_name" => "UKALJAZEERA",
				"otrkeyfile_name" => "ukaljazeera",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKBBC",
				"otrkeyfile_name" => "ukbbc",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKBBC2",
				"otrkeyfile_name" => "ukbbc2",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKBBC3",
				"otrkeyfile_name" => "ukbbc3",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKBBC4",
				"otrkeyfile_name" => "ukbbc4",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKCBBC",
				"otrkeyfile_name" => "ukcbbc",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKCBEEBIES",
				"otrkeyfile_name" => "ukcbeebies",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKCBSACTION",
				"otrkeyfile_name" => "ukcbsaction",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKCBSDRAMA",
				"otrkeyfile_name" => "ukcbsdrama",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKCHANNEL4",
				"otrkeyfile_name" => "ukchannel4",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKCITV",
				"otrkeyfile_name" => "ukcitv",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKE4",
				"otrkeyfile_name" => "uke4",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKFILM4",
				"otrkeyfile_name" => "ukfilm4",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKHORROR",
				"otrkeyfile_name" => "ukhorror",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKITV",
				"otrkeyfile_name" => "ukitv",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKITV2",
				"otrkeyfile_name" => "ukitv2",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKITV3",
				"otrkeyfile_name" => "ukitv3",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKITV4",
				"otrkeyfile_name" => "ukitv4",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKMORE4",
				"otrkeyfile_name" => "ukmore4",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKMOVIES4MEN",
				"otrkeyfile_name" => "ukmovies4men",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKTRUEENTERTAINMENT",
				"otrkeyfile_name" => "uktrueentertainment",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKTRUEMOVIES1",
				"otrkeyfile_name" => "uktruemovies1",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "UKTRUEMOVIES2",
				"otrkeyfile_name" => "uktruemovies2",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USANTENNATV",
				"otrkeyfile_name" => "usantennatv",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USBOUNCETV",
				"otrkeyfile_name" => "usbouncetv",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USMOVIES",
				"otrkeyfile_name" => "usmovies",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USNJTV",
				"otrkeyfile_name" => "usnjtv",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USTHISTV",
				"otrkeyfile_name" => "usthistv",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USWABC",
				"otrkeyfile_name" => "uswabc",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USWCBS",
				"otrkeyfile_name" => "uswcbs",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USWFUT",
				"otrkeyfile_name" => "uswfut",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "USWNBC",
				"otrkeyfile_name" => "uswnbc",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USWNJU",
				"otrkeyfile_name" => "uswnju",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "USWNYE",
				"otrkeyfile_name" => "uswnye",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USWNYW",
				"otrkeyfile_name" => "uswnyw",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USWPIX",
				"otrkeyfile_name" => "uswpix",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USWWOR",
				"otrkeyfile_name" => "uswwor",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "USWXTV",
				"otrkeyfile_name" => "uswxtv",
				"language" => "Spanisch",
				"language_short" => "es",
			),
			array(
				"tvprogram_name" => "VIVA",
				"otrkeyfile_name" => "viva",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "VOX",
				"otrkeyfile_name" => "vox",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "W9",
				"otrkeyfile_name" => "w9",
				"language" => "Französisch",
				"language_short" => "fr",
			),
			array(
				"tvprogram_name" => "WDR",
				"otrkeyfile_name" => "wdr",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "WELTDERWUNDER",
				"otrkeyfile_name" => "weltderwunder",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ZDF",
				"otrkeyfile_name" => "zdf",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ZDF INFO",
				"otrkeyfile_name" => "zdfinfo",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ZDFKULTUR",
				"otrkeyfile_name" => "zdfkultur",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ZDF NEO",
				"otrkeyfile_name" => "zdfneo",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SERVUSTV",
				"otrkeyfile_name" => "servustv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "PULS8",
				"otrkeyfile_name" => "puls8",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "RHEINMAINTV",
				"otrkeyfile_name" => "rheinmaintv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "MELODIETV",
				"otrkeyfile_name" => "melodietv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "BVN",
				"otrkeyfile_name" => "bvn",
				"language" => "Niederländisch",
				"language_short" => "nl",
			),
			array(
				"tvprogram_name" => "RTLPLUS",
				"otrkeyfile_name" => "rtlplus",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "FAMILYTV",
				"otrkeyfile_name" => "familytv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ZEEONE",
				"otrkeyfile_name" => "zeeone",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SWR",
				"otrkeyfile_name" => "swr",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "KABEL1DOKU",
				"otrkeyfile_name" => "kabel1doku",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ARDALPHA",
				"otrkeyfile_name" => "ardalpha",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "ONE",
				"otrkeyfile_name" => "one",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "HR",
				"otrkeyfile_name" => "hr",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "TV24",
				"otrkeyfile_name" => "tv24",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "TV25",
				"otrkeyfile_name" => "tv25",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "EOTV",
				"otrkeyfile_name" => "eotv",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "H2D",
				"otrkeyfile_name" => "h2d",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "SKYSPORTNEWS",
				"otrkeyfile_name" => "skysportnews",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "UKDRAMA",
				"otrkeyfile_name" => "ukdrama",
				"language" => "Englisch",
				"language_short" => "en",
			),
			array(
				"tvprogram_name" => "NICKAUSTRIA",
				"otrkeyfile_name" => "nickaustria",
				"language" => "Deutsch",
				"language_short" => "de",
			),
			array(
				"tvprogram_name" => "UKMOVIES4MEN",
				"otrkeyfile_name" => "ukmovies4men",
				"language" => "Englisch",
				"language_short" => "en",
			),
		);
		
		foreach($stations as $station) {
	        DB::table('stations')->insert([
				'tvprogram_name' => $station['tvprogram_name'],
				'otrkeyfile_name' => $station['otrkeyfile_name'],
				'language' => $station['language'],
				'language_short' => $station['language_short'],
				'created_at' => DB::raw('NOW()'),
				'updated_at' => DB::raw('NOW()'),
			]);

			
		}
    }
}
